### ISSUE TITLE
Add config.yml instructions in README

### ISSUE THREAD

**Issue by bladedevoff** [BlueprintFramework/docker#9]
Hi! I suggest adding instructions to the README for config.yml, I was constantly encountering problems with binding in cwings today until I remembered about directories in config.yml.

Example:

root_directory: /srv/pterodactyl
log_directory: /var/log/pterodactyl
data: /srv/pterodactyl/volumes
archive_directory: /srv/pterodactyl/archives
backup_directory: /srv/pterodactyl/backups
tmp_directory: /tmp/pterodactyl

Add for dumb people like me :)

**Comment by Loki-101** [comment]
Thanks for the suggestion. A section has been added covering mounts in https://github.com/BlueprintFramework/docker/commit/b01b0dbef3799dd4369296fe5bd369bce09262ab
